### ISSUE TITLE
Cannot find name 'EventBuildPayloadBase'

### ISSUE THREAD

**Issue by thomastsaidotcom** [nanostores/logger#17]
Error: node_modules/@nanostores/logger/build-creator-logger/index.d.ts:30:20 - error TS2304: Cannot find name 'EventBuildPayloadBase'.

```
build: (payload: EventBuildPayloadBase) => void
```

**Comment by euaaaio** [comment]
`creatorLogger` is only needed to work with `mapTemplate`, which is deprecated. We removed it because it can be implemented by yourself in a few lines of code. Perhaps in the future we'll bring it back in a a bit different form or as a separate advanced package.

Why are you using `creatorLogger()` instead of `logger()`?

**Comment by euaaaio** [comment]
I misunderstood you. We have a typo in types.

**Comment by euaaaio** [comment]
Thanks for issue. Fixed in v0.2.4
